#!/usr/bin/env python3
"""Mix local backing music into a completed SFX video; never calls Mirelo."""
import argparse
import json
import os
from pathlib import Path
import subprocess
import tempfile


DEFAULT_MUSIC = Path(__file__).resolve().parent / "examples/arcade-backing.wav"


def probe(path):
    if not path.is_file():
        raise ValueError(f"Input file missing: {path}")
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_streams", "-show_format", "-of", "json", str(path)],
        check=True, capture_output=True, text=True,
    )
    return json.loads(result.stdout)


def mix(video, music, out):
    video, music, out = (Path(p).expanduser().resolve() for p in (video, music, out))
    if out in (video, music) or out.exists():
        raise ValueError("Choose a new output path; existing inputs and outputs are preserved")
    source, backing = probe(video), probe(music)
    kinds = {s["codec_type"] for s in source["streams"]}
    if not {"video", "audio"}.issubset(kinds):
        raise ValueError("Video must contain video and generated SFX audio")
    if not any(s["codec_type"] == "audio" for s in backing["streams"]):
        raise ValueError("Music must contain audio")
    duration = float(source["format"]["duration"])
    if float(backing["format"]["duration"]) + 0.05 < duration:
        raise ValueError("Music is shorter than the video; supply a matching backing track")
    if music == DEFAULT_MUSIC.resolve() and abs(duration - 8.0) > 0.05:
        raise ValueError("Bundled music is only for the eight-second arcade demo")
    out.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="mirelo-music-", dir=out.parent) as temp:
        staged = Path(temp) / "mixed.mp4"
        subprocess.run([
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-nostdin",
            "-i", str(video), "-i", str(music), "-filter_complex",
            "[0:a:0]aresample=48000[sfx];[1:a:0]aresample=48000,volume=0.8[music];"
            "[sfx][music]amix=inputs=2:duration=first:normalize=0,alimiter=limit=0.95:level=false:latency=true[a]",
            "-map", "0:v:0", "-map", "[a]", "-c:v", "copy", "-c:a", "aac",
            "-b:a", "192k", "-t", str(duration), "-movflags", "+faststart", str(staged),
        ], check=True, capture_output=True, text=True)
        result = probe(staged)
        if abs(float(result["format"]["duration"]) - duration) > 0.1:
            raise ValueError("Mixed output duration does not match source")
        os.link(staged, out)  # Atomically refuse overwrite, including concurrent writers.
    return {"status": "done", "credits_spent": 0, "duration_seconds": duration,
            "music_source": "local backing track; not generated by Mirelo",
            "files": {"source_video": str(video), "music": str(music), "with_music": str(out)}}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--video", required=True, help="Completed video with SFX audio")
    parser.add_argument("--music", default=str(DEFAULT_MUSIC), help="Local backing track (default: original arcade music)")
    parser.add_argument("--out", required=True, help="New MP4 output path")
    args = parser.parse_args()
    try:
        result = mix(args.video, args.music, args.out)
    except (ValueError, OSError, subprocess.CalledProcessError) as exc:
        print(json.dumps({"status": "error", "message": str(exc)}))
        return 1
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
